### ISSUE TITLE
support multiple instances via webpack options

### ISSUE THREAD

**Issue by mikestaub** [GoogleChromeLabs/comlink-loader#8]
When I try to use the `options.multiple = true` feature via my webpack config like so:

```
module: {
      {
        test: /\.worker\.js$/,
        use: {
          loader: 'comlink-loader',
          options: { inline: true, multiple: false }
        },
      },
}
```

I get this error:
```
Module build failed: ValidationError: Worker Loader Invalid Options
options['multiple'] is an invalid additional property
```

A workaround is to just delete that property in the options object after it is checked.

**Comment by developit** [comment]
Hiya! Apologies for dropping this issue on the ground. I've just published 1.1.1 that fixes it.
